# Generated by Django 4.0.2 on 2022-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewAni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='番名')),
                ('date', models.CharField(max_length=8, verbose_name='日期')),
                ('day_of_week', models.IntegerField(verbose_name='星期')),
                ('pub_index', models.CharField(max_length=16, verbose_name='更新集数')),
                ('pub_time', models.CharField(max_length=8, verbose_name='更新时间')),
                ('season_id', models.IntegerField(verbose_name='seasonid')),
                ('cover', models.ImageField(upload_to='', verbose_name='cover')),
                ('ep_cover', models.ImageField(upload_to='', verbose_name='epcover')),
                ('square_cover', models.ImageField(upload_to='', verbose_name='squarecover')),
                ('episode_id', models.IntegerField(blank=True, null=True, verbose_name='episode_id')),
                ('vedio_addr', models.CharField(blank=True, max_length=256, null=True, verbose_name='播放地址')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='番名')),
                ('viewers', models.CharField(max_length=16, verbose_name='观众数')),
                ('likers', models.CharField(max_length=16, verbose_name='收藏数')),
                ('addr', models.CharField(max_length=256, verbose_name='播放地址')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
